#!/bin/bash

echo """,16,32,64,128" >> "project5.csv"

for trials in 2 4 8 16 32 64 128 256 512 1000
do
    for sizes in 16 32 64 128
    do
        echo -n "$trials" >> "project5.csv"
        /usr/local/apps/cuda/cuda-10.1/bin/nvcc -DBLOCKSIZE=$sizes -DNUMTRIALS=$((1024*$trials)) -o project5 project5.cu
        ./project5
    done
    echo >> "project5.csv"
done

rm project5
